#!/bin/bash

_die() {
	[[ $1 != "" ]] && echo "$1"
	echo "Terminating"
	exit 1
}

_check_components() {
	which $compil &>/dev/null
	(( $? == 1 )) && _die "No $compil compiler"

	which "sed" &>/dev/null
	(( $? == 1 )) && _die "No sed installed"

	which "grep" &>/dev/null
	(( $? == 1 )) && _die "No grep installed"

	which "awk" &>/dev/null
	(( $? == 1 )) && _die "No awk installed"

	which "realpath" &>/dev/null
	(( $? == 1 )) && _die "No realpath installed"
}

isProfEx() {
	[[ -n "$(awk -v r="^$1:" '/r/ {print $0}' "$profilef")" ]] && return 0
	return 1
}

save_profiel() {
	isProfEx $3
	(( $? == 0 )) && return
	printf "$3:$(realpath $1):$(realpath $2)\n" >> "$profilef"
}

del_profile() {
	# isProfEx $1 || return 1
	sed "/^$1*/d" "$profilef"
}

load_profile() {
	inp="$(awk -v p="^$1" -F':' '/p/ {print $2}' "$profilef")"
	outp="$(awk -v p="^$1" -F':' '/p/ {print $3}' "$profilef")"
}

_check_arg() {
	[[ -z $1 || ! -f $1 ]] && emsg="Missing input file"
	if [[ -z $2 || ! -f $2 ]]; then
		if [[ -n $emsg ]]; then
			emsg+=" and output file"
		else
			emsg="Missing output file"
		fi
	fi
	[[ -n $emsg ]] && _die "$emsg"
}

_check_input() {
	isProfEx $1
	[[ $? == 0 ]] && load_profile $1 && return

	if [[ $1 == "-s" ]]; then
		_check_arg $3 $4
		save_profiel $3 $4 $2
		load_profile $2
	fi
}

compil="sassc"
profilef="$HOME/.upds"
[[ -f "$profilef" ]] || >"$profilef"

inp="$1"
outp="$2"
_check_components
_check_input $1 $2 $3 $4

$compil "$inp" "$outp"
if [[ $? == 0 ]]; then
	echo "Styles succesfuly updated"
else
	echo "Cant update styles"
fi
