#!/bin/bash

_die() {
	[[ $1 != "" ]] && echo "$1"
	echo "Terminating"
	exit 1
}

_check_components() {
	which $compil &>/dev/null
	(( $? == 1 )) && _die "No $compil compiler"

	which "sed" &>/dev/null
	(( $? == 1 )) && _die "No sed installed"

	which "grep" &>/dev/null
	(( $? == 1 )) && _die "No grep installed"

	which "awk" &>/dev/null
	(( $? == 1 )) && _die "No awk installed"

	which "realpath" &>/dev/null
	(( $? == 1 )) && _die "No realpath installed"
}

compile() {
	$compil "$1" "$2"
	if [[ $? == 0 ]]; then
		echo "Styles succesfuly updated"
	else
		echo "Cant update styles"
	fi
}

isProfEx() {
	[[ -n $(grep "^${1}:" "$profilef") ]] && return 0
	return 1
}

save_profile() {
	isProfEx $3
	(( $? == 0 )) && return
	printf "$3:$(realpath $1):$(realpath $2)\n" >> "$profilef"
}

del_profile() {
	# isProfEx $1 || return 1
	sed "/^$1*/d" "$profilef"
}

get_profile_prop() {
	if [[ -n $3 ]]; then
		awk -v p="$1" -v field="${2}" -F':' '{ if($1 == p) {print $field} }' <<< "${3}"
	else
		awk -v p="$1" -v field="${2}" -F':' '{ if($1 == p) {print $field} }' "${profilef}"
	fi
}

load_all() {
	while read prof; do
		compile "$(get_profile_prop \  2 "$prof")" "$(get_profile_prop \  3 "$prof")" 
	done <<< $(cat "$profilef")
}

load_profile() {
	[[ $1 == "all" ]] && load_all
	inp=$(get_profile_prop $1 2)
	outp=$(get_profile_prop $1 3)
	compile "$inp" "$outp"
}

_check_arg() {
	[[ -z $1 || ! -f $1 ]] && emsg="Missing input file"
	if [[ -z $2 || ! -f $2 ]]; then
		if [[ -n $emsg ]]; then
			emsg+=" and output file"
		else
			emsg="Missing output file"
		fi
	fi
	[[ -n $emsg ]] && _die "$emsg"
}

_check_input() {
	if [[ $1 == "-s" ]]; then
		_check_arg $3 $4
		save_profile $3 $4 $2
		load_profile $2
		return
	fi

	isProfEx $1
	[[ $? == 0 ]] && load_profile $1 && return

	compile $1 $2
}

compil="sassc"
profilef="$HOME/.upds"
[[ -f "$profilef" ]] || >"$profilef"

_check_components
_check_input $1 $2 $3 $4
