#!/bin/bash

_die() {
	[[ $1 != "" ]] && echo "$1"
	echo "Terminating"
	exit 1
}

_check_components() {
	which $compil &>/dev/null
	(( $? == 1 )) && _die "No $compil compiler"

	which "sed" &>/dev/null
	(( $? == 1 )) && _die "No sed installed"
}

isProfEx() {
	[[ -n $(grep "'$1'" "$profilef") ]] && return 0
	return 1
}

save_profiel() {
	printf "$3:$1:$2\n" >> "$profilef"
}

del_profile() {
	# isProfEx $1 || return 1
	sed "/^$1*/d" "$profilef"
}

load_profile() {
	inp=
	outp=
}

_check_input() {
	[[ $(isProfEx $1) == 0 ]] && load_profile $1 && return

	[[ -z $1 || ! -f $1 ]] && emsg="Missing input file"
	if [[ -z $2 || ! -f $2 ]]; then
		if [[ -n $emsg ]]; then
			emsg+=" and output file"
		else
			emsg="Missing output file"
		fi
	fi
	[[ -n $emsg ]] && _die "$emsg"

	if [[ $1 == "-s" ]]; then
		save_profiel $3 $4 $2
		load_profile $2
	fi
}

compil="sassc"
profilef="$HOME/.upds"
[[ -f "$profilef" ]] || >"$profilef"

inp="$1"
outp="$2"
_check_components
_check_input $1 $2 $3 $4

$compil "$inp" "$outp"
if [[ $? == 0 ]]; then
	echo "Styles succesfuly updated"
else
	echo "Cant update styles"
fi
